name: Sign My Android APK

on:
  workflow_dispatch: # هذا الخيار يتيح لك تشغيل التوقيع يدوياً بضغطة زر في أي وقت

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Sign APK File
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASS }}

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Signed-APK-Application
          path: app-unsigned-signed.apk
